A PR for Contact form where we set up the contact
KALUNGI-J-BOBSON/Portfolio-finish-mobile-version pull request #5
Opened 2022-12-13 15:18 UTC by KALUNGI-J-BOBSON

Added the form section
Added the MIT license
Setup linters for the index.html  and style.css

2022-12-13 15:37 UTC, frank1738 requested changes
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/11ISwbgCxEzMyY/giphy.gif"/>


## Highlights

✅ Correct use of Github workflow
✅ No linter error
✅ README is okay
✅ Form submission working properly 👍 


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-13 15:37 UTC, frank1738 commented on index.html
>            method="post"
- [ ] Kindly adjust the padding of your inputs to match the original design.

![image](https://user-images.githubusercontent.com/98453979/207375711-27da6201-25ab-4350-945b-b1825948c466.png)


### Checkout original design

![image](https://user-images.githubusercontent.com/98453979/207375800-dab2d03a-794e-4961-bc05-ab500e6f9962.png)

2022-12-14 08:35 UTC, enniopo commented
Hi @KALUNGI-J-BOBSON - please go ahead and submit another review request when you are done implementing the changes requested by the CR. Thank you, and sorry for the inconvenience.

2022-12-14 08:43 UTC, KALUNGI-J-BOBSON commented
I have implemented the changes ambut i dont have a review button i have
only the submit button

On Wed, Dec 14, 2022 at 11:35 ennio ***@***.***> wrote:

> Hi @KALUNGI-J-BOBSON <https://github.com/KALUNGI-J-BOBSON> - please go
> ahead and submit another review request when you are done implementing the
> changes requested by the CR. Thank you, and sorry for the inconvenience.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KALUNGI-J-BOBSON/Portfolio-finish-mobile-version/pull/5#issuecomment-1350634235>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXGWXK6O4JLHSTEOUJ4XH3WNGBF3ANCNFSM6AAAAAAS5KVB6Q>
> .
> You are receiving this because you were mentioned.Message ID:
> <KALUNGI-J-BOBSON/Portfolio-finish-mobile-version/pull/5/c1350634235@
> github.com>
>

2022-12-14 09:22 UTC, KALUNGI-J-BOBSON commented
Hello
Thanks
Iam trying to request another review having finished implementation of what
the previous CR asked me
But i see it tell me “You have no review requests to rate for this activity”

What can I do?

On Wed, Dec 14, 2022 at 11:43 Kalungi J Bobson ***@***.***>
wrote:

> I have implemented the changes ambut i dont have a review button i have
> only the submit button
>
> On Wed, Dec 14, 2022 at 11:35 ennio ***@***.***> wrote:
>
>> Hi @KALUNGI-J-BOBSON <https://github.com/KALUNGI-J-BOBSON> - please go
>> ahead and submit another review request when you are done implementing the
>> changes requested by the CR. Thank you, and sorry for the inconvenience.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/KALUNGI-J-BOBSON/Portfolio-finish-mobile-version/pull/5#issuecomment-1350634235>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AZXGWXK6O4JLHSTEOUJ4XH3WNGBF3ANCNFSM6AAAAAAS5KVB6Q>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> <KALUNGI-J-BOBSON/Portfolio-finish-mobile-version/pull/5/c1350634235@
>> github.com>
>>
>

2022-12-14 10:50 UTC, KALUNGI-J-BOBSON commented
Hello,i hope you are doing well,
I am trying to request for a review on my project but it shows me “you have
no review requests to rate for this activity “
Kindly help me out thanks
On Wed, Dec 14, 2022 at 12:21 Kalungi J Bobson ***@***.***>
wrote:

> Hello
> Thanks
> Iam trying to request another review having finished implementation of
> what the previous CR asked me
> But i see it tell me “You have no review requests to rate for this
> activity”
>
> What can I do?
>
> On Wed, Dec 14, 2022 at 11:43 Kalungi J Bobson ***@***.***>
> wrote:
>
>> I have implemented the changes ambut i dont have a review button i have
>> only the submit button
>>
>> On Wed, Dec 14, 2022 at 11:35 ennio ***@***.***> wrote:
>>
>>> Hi @KALUNGI-J-BOBSON <https://github.com/KALUNGI-J-BOBSON> - please go
>>> ahead and submit another review request when you are done implementing the
>>> changes requested by the CR. Thank you, and sorry for the inconvenience.
>>>
>>> —
>>> Reply to this email directly, view it on GitHub
>>> <https://github.com/KALUNGI-J-BOBSON/Portfolio-finish-mobile-version/pull/5#issuecomment-1350634235>,
>>> or unsubscribe
>>> <https://github.com/notifications/unsubscribe-auth/AZXGWXK6O4JLHSTEOUJ4XH3WNGBF3ANCNFSM6AAAAAAS5KVB6Q>
>>> .
>>> You are receiving this because you were mentioned.Message ID:
>>> <KALUNGI-J-BOBSON/Portfolio-finish-mobile-version/pull/5/c1350634235@
>>> github.com>
>>>
>>

2022-12-14 11:23 UTC, enniopo commented
@KALUNGI-J-BOBSON let me check this

2022-12-14 11:29 UTC, enniopo commented
@KALUNGI-J-BOBSON you should be able to request a review now.

2022-12-14 11:30 UTC, KALUNGI-J-BOBSON commented
Hello
I have just tried now after this mail
I stil can’t request for a review

On Wed, Dec 14, 2022 at 14:29 ennio ***@***.***> wrote:

> @KALUNGI-J-BOBSON <https://github.com/KALUNGI-J-BOBSON> you should be
> able to request a review now.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/KALUNGI-J-BOBSON/Portfolio-finish-mobile-version/pull/5#issuecomment-1351056759>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AZXGWXO4QIYPC4YBZUDR6KLWNGVQZANCNFSM6AAAAAAS5KVB6Q>
> .
> You are receiving this because you were mentioned.Message ID:
> <KALUNGI-J-BOBSON/Portfolio-finish-mobile-version/pull/5/c1351056759@
> github.com>
>

2022-12-14 11:31 UTC, KALUNGI-J-BOBSON commented
Thanks it had come now
Iam able

On Wed, Dec 14, 2022 at 14:30 Kalungi J Bobson ***@***.***>
wrote:

> Hello
> I have just tried now after this mail
> I stil can’t request for a review
>
> On Wed, Dec 14, 2022 at 14:29 ennio ***@***.***> wrote:
>
>> @KALUNGI-J-BOBSON <https://github.com/KALUNGI-J-BOBSON> you should be
>> able to request a review now.
>>
>> —
>> Reply to this email directly, view it on GitHub
>> <https://github.com/KALUNGI-J-BOBSON/Portfolio-finish-mobile-version/pull/5#issuecomment-1351056759>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AZXGWXO4QIYPC4YBZUDR6KLWNGVQZANCNFSM6AAAAAAS5KVB6Q>
>> .
>> You are receiving this because you were mentioned.Message ID:
>> <KALUNGI-J-BOBSON/Portfolio-finish-mobile-version/pull/5/c1351056759@
>> github.com>
>>
>

2022-12-14 11:40 UTC, Olamarx approved these changes
Hi @KALUNGI-J-BOBSON,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
<img src="https://media1.giphy.com/media/3oz9ZE2Oo9zRC/giphy.gif"/>
## Highlights
- Linters passed ✔️ 
- Contact form 👍🏼 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-12-14 11:41 UTC, merged